version: '3.3'

services:

  db:
    image: mariadb:10.4.7
    container_name: db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - database:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_HOST=db
    ports:
      - 8080:80

  wordpress:
    image: wordpress:5.2.2
    container_name: wordpress
    depends_on:
      - db
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  database:
